// MARK: - Styles
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  darkContainer: {
    backgroundColor: "black",
  },
  searchContainerWrapper: {
    padding: 10,
    paddingBottom: 5,
  },
  searchContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    backgroundColor: "white",
    borderRadius: 10,
    elevation: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.95,
    shadowRadius: 13.84,
  },
  darkSearchContainer: {
    backgroundColor: "#2C2C2E",
  },
  searchBarContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 10,
  },
  searchBar: {
    flex: 1,
    fontSize: 18,
    color: "black",
  },
  darkSearchBar: {
    color: "white",
  },
  clearButton: {
    padding: 5,
  },
  filterButton: {
    padding: 5,
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "bold",
  },
  toggleButton: {
    padding: 5,
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "bold",
  },
  list: {
    backgroundColor: "white",
  },
  darkList: {
    backgroundColor: "black",
  },
  row: {
    flexDirection: "row",
    padding: 15,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    alignItems: "center",
    justifyContent: "space-between",
  },
  darkRow: {
    backgroundColor: "#1C1C1E",
    borderBottomColor: "#2C2C2E",
  },
  number: {
    fontSize: 18,
    width: 30,
    textAlign: "center",
    fontWeight: "300",
    color: "black",
    opacity: 0.75,
  },
  title: {
    fontSize: 18,
    fontWeight: "500",
    marginLeft: 10,
    flex: 1,
    color: "black",
  },
  darkText: {
    color: "white",
  },
  statusIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginLeft: 10,
  },
  visited: {
    backgroundColor: "#4CAF50",
  },
  notVisited: {
    backgroundColor: "#F44336",
  },
  heartContainer: {
    padding: 5,
  },
  gridItem: {
    flex: 1,
    margin: 10,
    justifyContent: "center",
    alignItems: "center",
    height: 165,
    backgroundColor: "white",
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.95,
    shadowRadius: 3.84,
    elevation: 7.5,
  },
  darkGridItem: {
    backgroundColor: "#1C1C1E",
    shadowColor: "#FFF",
  },
  imageContainer: {
    width: "100%",
    height: "100%",
    borderRadius: 15,
    overflow: "hidden",
  },
  gridImage: {
    width: "100%",
    height: "100%",
  },
  blurView: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  gridInfoContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  darkGridInfoContainer: {
    backgroundColor: "rgba(28, 28, 30, 0.85)",
  },
  gridNumber: {
    fontSize: 22,
    color: "black",
    fontWeight: "bold",
  },
  gridTitle: {
    fontSize: 18,
    color: "black",
  },
  popUp: {
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  popUpText: {
    color: "black",
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    backgroundColor: "white",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    elevation: 5,
  },
  darkPopUpText: {
    color: "white",
    backgroundColor: "#2C2C2E",
  },
});
